# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a49dd0575bd3f12348be650b9b996101676c51ed4d6248a6f0de049acbd56d89c0492c06465f38e01fd9d8e14117dad7c969fd3c7dd92d7bda8ef223cfebc88

test:
  secret_key_base: 40b3253533649b9367d82c92894cb3d13d945e3b7062301ece71f0113f35fe6b2902d724a79707493432ad7b2d043b71de2072d3d86a4ce7f878d295a8723464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
